### ISSUE TITLE
Descriptor Not working

### ISSUE THREAD

**Issue by BikshapathiM** [Adam-Langley/pybleno#11]
I added descriptor in my characteristic and i am  trying to read the descriptor value from master side, then its giving error like as below...
**Error :** 
Exception in thread HCISocketPoller:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/BluetoothHCI/BluetoothHCI.py", line 197, in _socket_poller
    self._socket_on_data_user_callback(bytearray(data))
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Hci.py", line 417, in onSocketData
    self.emit('aclDataPkt', [handle, cid, pktData])
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Emit.py", line 15, in emit
    handler(*arguments)
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Bindings.py", line 167, in onAclDataPkt
    self._aclStream.push(cid, data)
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/AclStream.py", line 18, in push
    self.emit('data', [cid, data])
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Emit.py", line 15, in emit
    handler(*arguments)
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Gatt.py", line 255, in onAclStreamData
    self.handleRequest(data)
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Gatt.py", line 299, in handleRequest
    response = self.handleReadOrReadBlobRequest(request)
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Gatt.py", line 725, in handleReadOrReadBlobRequest
    callback(result, data)
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Gatt.py", line 665, in callback
    callbackResponse[1 + i] = data[i]
TypeError: an integer is required

**my code :** 
def __init__(self):
        Characteristic.__init__(self, {
            'uuid': '13333333333333333333333333330001',
            'properties': ['read', 'write','notify'],
            'descriptors':[
                Descriptor(
                        uuid = '2901',
                        value = 'Buld_characteristic'
                )],
            'value': None
        })

**Comment by Adam-Langley** [comment]
Hi @BikshapathiM - bleno had a constructor shortcut that allows you to pass string values instead of buffers to the Descriptor. I hadn't implemented it. It has been fixed in Pypi v0.7
Pull latest to fix this issue.
Or, you can work around by passing an array of bytes to the Descriptor instead.
