### ISSUE TITLE
error while writing to characteristics from nrf connect app 

### ISSUE THREAD

**Issue by sherifshsffa91** [Adam-Langley/pybleno#25]
hello Adam ,

i have a problem while I am trying to write any type of data to characteristics it returns that error from any android device using (nrf connect app) while if I tried from Iphone it done with no problem.

this is the error
```
Exception in thread HCISocketPoller:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/BluetoothHCI/BluetoothHCI.py", line 197, in _socket_poller
    self._socket_on_data_user_callback(bytearray(data))
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Hci.py", line 412, in onSocketData
    self.emit('aclDataPkt', [handle, cid, pktData])
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Emit.py", line 15, in emit
    handler(*arguments)
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Bindings.py", line 167, in onAclDataPkt
    self._aclStream.push(cid, data)
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/AclStream.py", line 18, in push
    self.emit('data', [cid, data])
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Emit.py", line 15, in emit
    handler(*arguments)
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Gatt.py", line 255, in onAclStreamData
    self.handleRequest(data)
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Gatt.py", line 305, in handleRequest
    response = self.handlePrepareWriteRequest(request)
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/Gatt.py", line 875, in handlePrepareWriteRequest
    response = array.array('B', [0] * len(request.length))
AttributeError: 'bytearray' object has no attribute 'length'
```
while in my characteristics code is as follows
```
class station_id_char(Characteristic):
        def __init__(self,myuuid):
                Characteristic.__init__(self,{
                        'uuid':myuuid,
                        'properties':['read','write'],
                        'value':None
                })
                self._value = array.array('b','try')
                self._updateValueCallback = None

        def onReadRequest(self, offset, callback):
                print('read succeeded')
                callback(Characteristic.RESULT_SUCCESS,self._value)
        def onWriteRequest(self, data, offset, withoutResponse, callback):
                self._value=data
                print('received '+ str(data))
                if self._updateValueCallback:
                        self._updateValueCallback=self._value
                callback(Characteristic.RESULT_SUCCESS)
```

thanks in advance

**Comment by Adam-Langley** [comment]
Hi @sherifshsffa91 - please try this branch, there appears to be some code that was ported from Node incorrectly.

https://github.com/Adam-Langley/pybleno/tree/patch-write-from-android
