### ISSUE TITLE
HCISocketPoller

### ISSUE THREAD

**Issue by smrfeld** [Adam-Langley/pybleno#27]
1. Great project
2. I get the following error at the end of the echo example (with sudo):
```
Exception in thread HCISocketPoller (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/BluetoothHCI/BluetoothHCI.py", line 195, in _socket_poller
  File "/usr/local/lib/python2.7/dist-packages/pybleno/hci_socket/BluetoothHCI/BluetoothHCI.py", line 101, in kernel_disconnect_workarounds
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'version_info'
```

Using the originally Bleno library works on this system (Raspberry pi).

Any ideas where to look? Thanks!

**Comment by smrfeld** [comment]
Edit: fixed by adding time.sleep(5) before sys.exit....
