### ISSUE TITLE
Pizza Example does not work

### ISSUE THREAD

**Issue by msomeha** [Adam-Langley/pybleno#37]
I get the following error when I try to run the project.  Any solution for this issue?

Traceback (most recent call last):
  File "peripheral.py", line 25, in <module>
    pizzaService = PizzaService(Pizza())
  File "/home/pi/pybleno/examples/pizza/PizzaService.py", line 11, in __init__
    PizzaCrustCharacteristic(pizza),
  File "/home/pi/pybleno/examples/pizza/PizzaCrustCharacteristic.py", line 18, in __init__
    value = 'Gets or sets the type of pizza crust.'
TypeError: __init__() got an unexpected keyword argument 'uuid'

**Comment by msomeha** [comment]
Found the solution.  You just need to fix the string detection in the descriptor.
From this:
`if options['value'] is str:`
to this:
`if isinstance(options['value'], str):`

**Comment by ShinChoon** [comment]
No it is not

**Comment by ShinChoon** [comment]
> Found the solution. You just need to fix the string detection in the Descriptor.py. From this: `if options['value'] is str:` to this: `if isinstance(options['value'], str):`

No it is already edited but still has the same error

**Comment by JHorwitz1011** [comment]
anyone make any progress on this?

AFAIK it looks like a javascript to python conversion error...
