### ISSUE TITLE
Batteryservice example does not work

### ISSUE THREAD

**Issue by snowingyuki** [Adam-Langley/pybleno#50]
Hi Adam,

I try to use pybleno on Ubuntu 18.04(using NVIDIA jetson nano).
My goal is  to have a jetson nano(as a peripheral) send an integer to an iPad(as a central) which uses the CoreBluetooth framework.
So, I want to check pybleno's program(on jetson nano) can send an integer to the iPad app like LightBlue. 

First, I downloaded the pybleno like this:
$ git clone https://github.com/Adam-Langley/pybleno

Then, I tried batteryservice example like this:
$ sudo python3 main.py

I got this message on jetsons terminal.
Hit <ENTER> to disconnect
on -> stateChange: poweredOn
Exception in thread HCISocketPoller:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pybleno/hci_socket/BluetoothHCI/BluetoothHCI.py", line 197, in _socket_poller
    self._socket_on_data_user_callback(bytearray(data))
  File "/usr/local/lib/python3.6/dist-packages/pybleno/hci_socket/Hci.py", line 387, in onSocketData
    self.processCmdCompleteEvent(cmd, status, result)
  File "/usr/local/lib/python3.6/dist-packages/pybleno/hci_socket/Hci.py", line 488, in processCmdCompleteEvent
    self.emit('leAdvertiseEnableSet', [status])
  File "/usr/local/lib/python3.6/dist-packages/pybleno/hci_socket/Emit.py", line 17, in emit
    handler(*arguments)
  File "/usr/local/lib/python3.6/dist-packages/pybleno/hci_socket/Gap.py", line 190, in onHciLeAdvertiseEnableSet
    self.emit('advertisingStart', [error])
  File "/usr/local/lib/python3.6/dist-packages/pybleno/hci_socket/Emit.py", line 17, in emit
    handler(*arguments)
  File "/usr/local/lib/python3.6/dist-packages/pybleno/hci_socket/Bindings.py", line 115, in onAdvertisingStart
    self.emit('advertisingStart', [error])
  File "/usr/local/lib/python3.6/dist-packages/pybleno/hci_socket/Emit.py", line 17, in emit
    handler(*arguments)
  File "/usr/local/lib/python3.6/dist-packages/pybleno/Bleno.py", line 158, in onAdvertisingStart
    self.emit('advertisingStart', [error])
  File "/usr/local/lib/python3.6/dist-packages/pybleno/hci_socket/Emit.py", line 17, in emit
    handler(*arguments)
  File "main.py", line 20, in onAdvertisingStart
    print('on -> advertisingStart: ' + ('error ' + error if error else 'success'));
TypeError: must be str, not Exception

Thanks!

**Comment by snowingyuki** [comment]
Hi Adam,
When I use this command,
sudo hciconfig hci0 down
sudo hciconfig hci0 up
sudo python3 main.py

I got this error message.
Hit <ENTER> to disconnect
on -> stateChange: poweredOn
on -> advertisingStart: success
setServices: success
Exception in thread HCISocketPoller:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pybleno/hci_socket/BluetoothHCI/BluetoothHCI.py", line 194, in _socket_poller
    data = self._socket.recv(1024)         # blocking
BrokenPipeError: [Errno 32] Broken pipe

In this case, LightBlue on iPad can connect to batteryservice example program on jetson nano only about 30 seconds.

Thanks!
